### ISSUE TITLE
Image capture mode as jpg

### ISSUE THREAD

**Issue by rana01645** [tungs/timecut#24]
This library is using timesnap for capturing image, is there any way to capture image as jpg format from timecut and render the video from that jpg images?

Thanks in advance

**Comment by jameswright** [comment]
I'd like to second this request, would it be possible to add an option to timecut to specify JPG format. Specifically looking at ways of trying to speed up the process and reading another issue, it was suggested to us JPG as opposed to PNG.

p.s. Thank you for this great tool - much appreciated.

**Comment by jameswright** [comment]
Changing to JPEG had a dramatic impact on the speed of capture.

A 510 frame capture took...

199263 when saving the screenshots as JPEG
301397 when saving the screenshots as PNG

So using JPEG saved 1/3 of the processing time.

I figured out how to do it. I'm sorry I'm not a big github user so I don't know how to push these changes back (or even if I'm allowed), but what I did was this:

Edit the index.js so that:

Line 91 reads :     outputPattern = path.resolve(frameDirectory, 'image-%09d.jpeg');
Line 97 reads :     outputPattern: outputPattern,
line 98 reads :      screenshotType: 'jpeg'

Hope that helps someone.

p.s. Quality looks slightly reduced.

**Comment by Asheboy** [comment]
@jameswright The changes to support this have been pushed to timesnap, but need implementing timecut still, I believe.

**Comment by jameswright** [comment]
@Asheboy You are correct, I modified the timecut index.js file with the above changes and that worked for me.

**Comment by tungs** [comment]
This should now be an option as of v0.1.3, using [`--screenshot-type`](https://github.com/tungs/timecut#cli-options-screenshot-type) or [`config.screenshotType`](https://github.com/tungs/timecut#js-config-screenshot-type)
