### ISSUE TITLE
Does Timecut have an output that I can consume in the front end so as to render a progress bar?

### ISSUE THREAD

**Issue by ShetlandJ** [tungs/timecut#49]
I'm sorry if GH Issues isn't the correct avenue for this, but I wasn't sure where else to ask and I don't see it in the docs. Does Timecut emit any events upon each frame being created so that I can emit that message and use it to render a progress bar?

**Comment by tungs** [comment]
Thanks for asking this! This indeed is the right place to ask questions and ask for new features.

There isn't currently an event model set up, though you probably can achieve the same result with one of a few different approaches. Off the top of my head, you can use [`config.preparePageForScreenshot`](https://github.com/tungs/timecut/#js-config-prepare-page-for-screenshot) on the node side of things or using `requestAnimationFrame` to run it client side.

### From node.js
Using [`config.preparePageForScreenshot`](https://github.com/tungs/timecut/#js-config-prepare-page-for-screenshot), you can run code on your client page before each screenshot. It'd look something like this (if for instance you're adjusting progress via an element with class `progress`):

```
timecut({
  //...
  preparePageForScreenshot(page, currentFrame, totalFrames) {
     // currentFrame is 1 based
     return page.evalute((currentFrame, totalFrames) => {
        document.querySelector('.progress').textContent = (currentFrame/ tf) * totalFrames + '%';
     }, currentFrame, totalFrames);
  }
});
```

Alternatively, if you've declared an update function in your client code like `updateProgress`:

```
timecut({
  //...
  preparePageForScreenshot(page, currentFrame, totalFrames) {
     return page.evalute((currentFrame, totalFrames) => {
        return updateProgress(currentFrame, totalFrames);
     }, currentFrame, totalFrames);
  }
});
```

### From the client code

Alternatively, if you want a client-only solution, you can use `requestAnimationFrame` which is overwritten to run once per captured frame. This has the disadvantage of not being aware of how many frames there are in total of being captured. Also you should be a little careful when running this, since there may be some cases where `requestAnimationFrame` is run without actually saving the frame. This may happen initially, or if `config.maximumAnimationFrameDuration` is set, if there are large delays between frames. An implementation could look something like this:

```
var currentFrame = 0;
function updateProgressDiv() {
  currentFrame++;
  document.querySelector('.progress').textContent = 'Frame: ' + currentFrame + 'Time: ' + Date.now();
  requestAnimationFrame(updateProgressDiv);
}
requestAnimationFrame(updateProgressDiv);
```

### Which should you use?

`config.preparePageForScreenshot` is more flexible and gives more information, but if you only want to edit client files or if the progress is based off of something that doesn't need that extra information, `requestAnimationFrame` may offer a more simple solution.

**Comment by ShetlandJ** [comment]
Thank you for your reply @tungs! I actually ended up with a solution yesterday, though it required a bit of JS wackiness to get the data that I needed. I have a websocket that speaks to timecut, and I used the logger portion to emit every time logger is hit:

(please excuse the currently rudimentary code, we're just testing it out but hoping to use it in production by Summer)

```
const render = (io) => {
    timecut({
        url: 'http://localhost:8080/templates/football',
        viewport: {
            width: 1920,
            height: 1080
        },
        fps: 25,
        duration: 2,
        transparentBackground: true,
        pipeMode: true,
        outputOptions: ['-c:v', 'prores_ks', '-pix_fmt', 'yuva444p10le'],
        screenshotType: 'jpeg',
        output: 'renders/alpha_video.mov',
        logger: (message) => {
            io.emit('timecut', {
                message: getMessage(message)
            });
        }
    }).then(function() {
        console.log('Done!');
    });
};
```

```
const getMessage = (message) => {
    const payload = {};

    if (message.includes('Capturing Frame')) {
        payload.type = 'frame_capture_message'
        payload.text = message.split(' ')[2].replace(/[ ,.]/g, "")
    } else {
        payload.type = 'default';
        payload.text = message
    }

    return payload;
}
```

Then in my Vue component, I used my $notifier to catch the emitted message:

```
    created() {
        this.$notifier.$on('timecut', this.handleProgressBar);
    },
```

Which hits this function:

```
        handleProgressBar({message}) {
            const totalFrames = 50;

            if (Number(message.text)) {
                this.progressValue = (Number(message.text) / totalFrames) * 100;
            }
        },
```

This produces this result:

![image](https://user-images.githubusercontent.com/29278616/111958832-9fea2c00-8ae5-11eb-834d-a2ffd37b1a6d.png)
![image](https://user-images.githubusercontent.com/29278616/111958866-a9739400-8ae5-11eb-9f70-2a6f8ccefa45.png)

**Comment by tungs** [comment]
That's great! Thanks for sharing
